### ISSUE TITLE
What do you think about disabling fuzzy when items are already filtered on backend?

### ISSUE THREAD

**Issue by frederikhors** [metonym/svelte-typeahead#28]
What do you think about disabling fuzzy when items are already filtered on backend?

**Comment by metonym** [comment]
Closed by #31 and released in [v4.1.0](https://github.com/metonym/svelte-typeahead/releases/tag/v4.1.0).

```svelte
<Typeahead value="abcd" {data} {extract} let:value>
  <svelte:fragment slot="no-results">
    No results found for "{value}"
  </svelte:fragment>
</Typeahead>
```

**Comment by metonym** [comment]
This component [exposes a `disabled` prop](https://github.com/metonym/svelte-typeahead#disabled-items) to mark specific items as disabled. The implementation should be left to the consumer if the items are filtered from the backend.

**Comment by beholdr** [comment]
Disabled items are not the same as filtered out by fuzzy search. Filtered out items not showing in results even as disabled. For example, I'm already has fuzzy search on the backend and it returns results even for query with typo. But fuzzy search on the client shows zero results because of fuzzy filtering out.

It would be very convenient to be able to disable fuzzy search completely.
